# Generated by Django 6.0.3 on 2026-05-08 14:42

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(default="US", max_length=2),
        ),
    ]
