# Generated by Django 6.0.3 on 2026-05-08 17:58

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_profile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="US",
                help_text="Used to show local streaming availability.",
                max_length=2,
            ),
        ),
    ]
