services:
  web:
    build: .
    image: movie-anime-discovery:latest
    ports:
      - "8080:8080"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      DATABASE_URL: "sqlite:////data/app.db"
      TMDB_TOKEN: ${TMDB_TOKEN}
    volumes:
      - sqlite_data:/data
    profiles: ["prod-test"]

volumes:
  sqlite_data: