# Generated by Django 6.0.3 on 2026-04-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("backdrop_path", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("original_title", models.CharField(max_length=50)),
                ("overview", models.CharField(max_length=250)),
                ("poster_path", models.CharField(max_length=250)),
                ("media_type", models.CharField(max_length=20)),
                ("original_language", models.CharField(max_length=20)),
                ("genre_ids", models.JSONField(default=list)),
                ("release_date", models.CharField(max_length=250)),
            ],
        ),
    ]
