# Generated by Django 6.0.3 on 2026-04-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="original_title",
        ),
        migrations.AddField(
            model_name="movie",
            name="adult",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_id",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="popularity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_average",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="vote_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="backdrop_path",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="original_language",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
