# Generated by Django 6.0.3 on 2026-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0002_remove_movie_original_title_movie_adult_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre_ids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
