# Generated by Django 6.0.3 on 2026-04-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0003_alter_movie_genre_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("genre_id", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre_ids",
        ),
        migrations.AddField(
            model_name="movie",
            name="genre_ids",
            field=models.ManyToManyField(to="media.moviegenre"),
        ),
    ]
