# Generated by Django 6.0.3 on 2026-04-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0004_moviegenre_remove_movie_genre_ids_movie_genre_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateTimeField(),
        ),
    ]
