# Generated by Django 6.0.3 on 2026-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0005_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
