# Generated by Django 6.0.3 on 2026-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0006_alter_movie_release_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_id", models.IntegerField(default=0, unique=True)),
                ("title", models.CharField(max_length=100)),
                ("averageScore", models.IntegerField(blank=True, default=0, null=True)),
                ("countryOfOrigin", models.CharField(max_length=3)),
                ("status", models.CharField(max_length=50)),
                ("episodes", models.IntegerField()),
                ("genres", models.ManyToManyField(to="media.animegenre")),
            ],
        ),
    ]
