# Generated by Django 6.0.3 on 2026-04-13 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0007_animegenre_anime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anime",
            old_name="countryOfOrigin",
            new_name="country_of_origin",
        ),
    ]
