# Generated by Django 6.0.3 on 2026-04-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0008_rename_countryoforigin_anime_country_of_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="episodes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
