# Generated by Django 6.0.3 on 2026-04-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0009_alter_anime_episodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="cover_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
