# Generated by Django 6.0.3 on 2026-04-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0010_anime_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
