# Generated by Django 6.0.3 on 2026-04-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0011_anime_slug_movie_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="anime",
            old_name="averageScore",
            new_name="score",
        ),
        migrations.AlterField(
            model_name="anime",
            name="media_id",
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
