# Generated by Django 6.0.3 on 2026-04-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0012_rename_averagescore_anime_score_alter_anime_media_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_id",
                    models.IntegerField(blank=True, default=0, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("cover_image", models.URLField(blank=True, null=True)),
                ("score", models.IntegerField(blank=True, default=0, null=True)),
                ("country_of_origin", models.CharField(max_length=3)),
                ("status", models.CharField(max_length=50)),
                ("episodes", models.IntegerField(blank=True, default=0, null=True)),
                ("genres", models.ManyToManyField(to="media.animegenre")),
            ],
        ),
    ]
