# Generated by Django 6.0.3 on 2026-04-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0013_manga"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
