# Generated by Django 6.0.3 on 2026-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0014_alter_manga_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="anime",
            name="title_english",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="anime",
            name="title_native",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="anime",
            name="title_romaji",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="title_english",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="title_native",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="title_romaji",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="manga",
            name="title",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
