# Generated by Django 6.0.3 on 2026-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0016_savedanime_savedmanga_savedmovie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_provider_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("logo_path", models.CharField(blank=True, max_length=200)),
                ("display_priority", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["display_priority", "name"],
            },
        ),
    ]
