# Generated by Django 6.0.3 on 2026-05-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0017_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamingOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("flatrate", "Flatrate"),
                            ("rent", "Rent"),
                            ("buy", "Buy"),
                            ("ads", "Free with ads"),
                            ("free", "Free"),
                        ],
                        max_length=10,
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="media.movie",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="offers",
                        to="media.service",
                    ),
                ),
            ],
            options={
                "ordering": ["service__display_priority", "service__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("movie", "service", "country", "offer_type"),
                        name="unique_offer_per_movie_service_country_type",
                    )
                ],
            },
        ),
    ]
