# Generated by Django 6.0.3 on 2026-05-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0018_streamingoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="backdrop_path",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster_path",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
    ]
