# Generated by Django 6.0.3 on 2026-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0019_alter_movie_backdrop_path_alter_movie_poster_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manga",
            name="episodes",
        ),
        migrations.AddField(
            model_name="anime",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="anime",
            name="format",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="anime",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="chapters",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="format",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="manga",
            name="volumes",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="manga",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="overview",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="popularity",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
